### ISSUE TITLE
Add Images button doesn't work.

### ISSUE THREAD

**Issue by Megalomaniak** [TwistedTwigleg/vanilla-bootstrap#13] opened 2019-04-01 10:15 UTC
Trying to use the button throws an error in developer console however for a user who doesn't know to look there it just seems to do nothing.

The error thrown:

    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.imgur.com/3/upload. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

MDN article for CORS:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by TwistedTwigleg** [comment] 2019-04-01 13:58
Hmm, I knew the Imgur plugin wasn't working when I tested it awhile ago, but at the time it seemed the rich post editor would just bypass the plugin.

I was planning at some point to see about ensuring the Imgur plugin works with the rich post editor, but this is a much more pressing issue (and maybe related to it seeming to bypass the rich editor). I'm guessing to fix this issue we'll need to edit the Imgur plugin itself.

Unless anyone else wants to take this, I do not mind trying my hand at fixing this.

**Comment by Megalomaniak** [comment] 2019-04-01 15:41
Well... give it a go, but I'm not against just dropping it from use in case we adopt the **Rich Editor** for the new theme/server. Also worth pointing out though that should there be enough demand from the users to stick with the old **Advanced Editor** and this has no issue with it then that might well be a solution too.

**Comment by TwistedTwigleg** [comment] 2019-04-01 16:36
> Well... give it a go, but I'm not against just dropping it from use in case we adopt the Rich Editor for the new theme/server.

That is true, we could just drop the plugin altogether. The only thing I would worry with dropping the Imgur plugin is server storage space. I can probably store a few GBs, maybe even a few hundred, before the server provider would have an issue, but as time goes on all of the images may amount to quite a bit of data.

That said, I suppose that is one of those "deal with it when we get there" problems, since there is no way of knowing whether the server provider will have an issue or not.

Maybe I can get the plugin to work with the Rich Editor as well as the Advance editor... Something to look into.

> Also worth pointing out though that should there be enough demand from the users to stick with the old Advanced Editor and this has no issue with it then that might well be a solution too.

Good point. If the Advance Editor is more popular then we can just use that instead of the Rich Editor.

That said, personally I think using the Rich Editor will make it easier to format posts from a end user point of view, as it is in my opinion much more intuitive. Though I'm not against using the Advance Editor if there is demand.

**Comment by Megalomaniak** [comment] 2019-04-01 17:28
> That said, personally I think using the Rich Editor will make it easier to format posts from a end user point of view, as it is in my opinion much more intuitive. Though I'm not against using the Advance Editor if there is demand.

Agreed. I've had to edit a many new users post.

**Comment by TwistedTwigleg** [comment] 2019-04-01 23:08
Well, I have good-ish news and bad news.

_____

The good-ish news is I found out how to fix the Cross-Origin Request Blocked issue. Turns out the plugin on Vanilla's site is actually not the latest version. On their site the plugin is version 1.1.10, while on Github it is 1.1.12. Using version 1.1.12 fixes the Cross-Origin Request Blocked issue entirely.

The bad news is, that now we get a new error instead, this one simply stating that the "Server responded with 0 code". [Another user](https://open.vanillaforums.com/discussion/37157/no-longer-works-server-responded-with-0-code) also got this issue, though no solutions have been found just yet.

Looking at Imgur's API, there is no information on a 0 code, so I'm not totally sure why it is not working. I looked through the plugin's code and found where it appears to be making the request, but according to the API spec that Imgur provides, it *should* work.

That said, I'll keep messing around with it for a bit longer and see what happens.

_____

**Edit**:

Yeah, I have no idea. I'm not the best Javascript developer, and whatever is causing the issue isn't providing enough information to debug what could be causing the issue.

On top of that, even if the plugin is fixed, it would still have to be interfaced with the Rich Editor. At first I thought this would be fairly trivial, but looking at the code I'm not so sure.

I thought about maybe just writing a custom plugin from scratch to make the Rich Editor work with Imgur, but I couldn't find any sort of API for the rich editor, nor did making edits to the files in plugins/RichEditor`, as the edits seem to be ignored. There is probably a compiling step or something, but I couldn't find anything on compiling a plugin, outside of compiling Vanilla itself, which I'm not too keen on given we'd either miss out on updates, or we'd have to apply our changes on top of the updates every time a update is released.

**I'm going to disable the plugin. I figure if my server provider has an issue with the potential file size accumulation, we can deal with it then.**

Closing this issue.

**Comment by Megalomaniak** [comment] 2019-04-02 00:46
But was it still working with the old advanced editor? We can always just go with the old one for milestone 1.0.0 and re-investigate the rich editor for future update.

**Comment by TwistedTwigleg** [comment] 2019-04-02 01:58
Sorry, I didn’t see this until now.

Yes and no. The old advance editor gives the “Server responded with 0 code” issue just like the add images button. I couldn’t figure out what a code of 0 signifies, but it doesn’t add a image so I’m guessing it is an error code.

**Comment by Megalomaniak** [comment] 2019-04-02 10:54
Well, one option still open to you is to open an issue on the plugins github, might be that it is a bug, also there is a forum for vanilla that help can be asked on.
https://open.vanillaforums.com/

**Comment by Megalomaniak** [comment] 2019-04-02 10:59
Also found this:

>  ajitbohra commented on May 18, 2015
> 
> Got it fixed my bad when moving from local to server forget to change the upload url which was pointing to local server.


> harshal-shinde commented on Aug 25, 2015
> 
> @ajitbohra : can you explain how you achieved this problem resolved by giving any short example. It will help us because currently i am facing same issue of server 0 error


> ajitbohra commented on Aug 26, 2015
> 
> @harshal-shinde in my case it was due to invalid upload path. If you can share the code can help you better


> jimmybaker commented on Oct 27, 2016
> 
> This can also happen when attempting to upload to Amazon S3 and you don't have the appropriate CORS configuration setup.

https://github.com/enyo/dropzone/issues/701

So it seems it might still be to do with the CORS.

and


> Response of server with code 0 means that request is not OK. You should read server error logs. There you will find the reason. I presume some server restrictions or rights set.
> 
> If server quits with 1 than request was executed = OK.

https://www.prestashop.com/forums/topic/624940-any-ideas-what-error-server-responded-with-0-code-means-when-uploading-module/?tab=comments#comment-2635448
So this might be your own server permissions/conf.

**Comment by Megalomaniak** [comment] 2019-04-02 11:12
Also found this, might come in handy:
https://www.test-cors.org/

**Comment by TwistedTwigleg** [comment] 2019-04-02 14:23
Interesting. Definitely something to look into!
Perhaps it is just a simple config/permissions issue after all.

______

**Edit: I found the issue!**

At line 145 in `imgurupload.js`, changing `url: "https://api.imgur.com/3/upload"` to `url: "https://api.imgur.com/3/upload/"` seems to fix the issue. Now it uploads to Imgur just fine.

I feel kinda stupid now, especially since the solution appears to be something so easy, but ah well! Live and learn I suppose.

Now I need to see about fixing a minor bug where it also uploads the image to the server, and then we'll be in business, at least with the Advance editor and the "Add images" button. Maybe adding support to the Rich editor will be something easy and small too. At least now I know the Imgur side of the plugin is working.

**Comment by Megalomaniak** [comment] 2019-04-02 19:04
Reopening then, for now this can actually be left in either triage or moved to low priority, since we only need to get it done for the release really.

**Comment by Megalomaniak** [comment] 2019-04-02 19:07
> At line 145 in `imgurupload.js`, changing `url: "https://api.imgur.com/3/upload"` to `url: "https://api.imgur.com/3/upload/"` seems to fix the issue. Now it uploads to Imgur just fine.

This the updated version from the github repo? Perhaps you should make a pull request there then.

**Comment by TwistedTwigleg** [comment] 2019-04-07 19:22
I uploaded a new version of the plugin to the [plugins repository](https://github.com/TwistedTwigleg/godot-forums-vanilla-plugins/tree/TwistedTwigleg_Working_Branch) to add support for the WYSIWYG post editor for the Advance Vanilla post editor.

I'm not sure if we want to use the WYSIWYG editor or not, but if we do, the plugin now supports it. Now I just need to see about fixing the drag-and-drop functionality so it uploads to Imgur, and then the plugin should be good to go.


I also left in a comment showing what appeared to be the correct HTML to get the plugin working with the Rich editor. It doesn't work, but if we decide to try adding support for the Rich post editor again, we'll at least have something to try.

**Comment by Megalomaniak** [comment] 2019-04-15 09:34
I suppose with the move back to advanced editor this can for the time being be closed. Leave that up to you though.

**Comment by TwistedTwigleg** [comment] 2019-04-15 12:43
Yeah, I agree. Now that we have a plugins repository, I figure issues with the Imgur plugin should probably go there anyway. Closing this issue...

**Closed as completed by TwistedTwigleg** 2019-04-15 12:43 UTC
Labels: bug
